services:
  app:
    container_name: nestjs-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      NODE_ENV: production
    restart: always
    networks:
      - backend
    env_file:
      - .env


networks:
  backend:
    name: qrcode_network
    driver: bridge

